# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5dc76b5ad46f2b6b08832b630d18554e8b21196639e287b98121f941086222608655b2f8309090cbbf53e9598be38683362540af2514b2bd34f37d16f8851cf6

test:
  secret_key_base: 2311a770e6c2fbee04b581ea0ff03d54dddf45cf64ea44c4acf3fd7d9654f543af2990ab85cf7b401a3fe6b574126c4180439dd8db5e4959faaf70c5c2beb776

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
